name: Jira CI/CD Integration

on:
  pull_request:
    types:
      - closed

jobs:
  update-jira-and-slack:
    if: github.event.pull_request.merged == true
    name: Update Jira & Notify Slack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Notify Slack
      if: ${{ steps.extract.outputs.issue != '' }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": ":white_check_mark: Jira issue *${{ steps.extract.outputs.issue }}* has been closed after PR was merged!"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
